apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certs.apisix.apache.org
spec:
  conversion:
    strategy: None
  group: apisix.apache.org
  names:
    kind: Cert
    listKind: CertList
    plural: certs
    singular: cert
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            data:
              properties:
              type: array
              items:
                type: object
                properties:
                  snis:
                    type: array
                    items:
                      type: string
                      parrern: ^(\*.){0,1}([0-9a-zA-Z][0-9a-zA-Z-]{0,62}.){1,4}[0-9a-zA-Z]{1,5}$
                    minItems: 1
                  cert:
                    type: string
                  key:
                    type: string
                  status:
                    type: integer
                    enum: [ 0, 1 ]
                    default: 1
                  exptime:
                    type: integer
                    minimum: 1588262400             #2020/5/1 0:0:0
                    maximum: 1598262400             #2020/5/1 0:0:0
                  validity_start:
                    type: integer
                  validity_end:
                    type: integer
                required: [ snis, cert, key ]
          required: [ data ]