{{- $ca := genCA "apisix-controller-ca" 365 }}
{{- $generate := printf "%s-apisix-controller.%s.svc" .Values.name .Release.Namespace }}
{{- $cert := genSignedCert $generate nil (list $generate) 365 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-apisix-controller-cert
  namespace: {{.Release.Namespace}}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: v1alpha1-{{.Values.name}}-apisix-controller
webhooks:
  - name: validtating.{{.Values.name}}.rules.v1alpha1
    admissionReviewVersions: [ v1 ]
    sideEffects: None
    timeoutSeconds: 15
    failurePolicy: Fail
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{.Values.name}}-apisix-controller
        namespace: {{.Release.Namespace}}
        path: /validating/apisix.apache.org/rules/v1alpha1
        port: 65443
    objectSelector:
      matchLabels:
        apisix.apache.org/controller-by: {{.Values.name}}
    rules:
      - apiGroups: [ apisix.apache.org ]
        apiVersions: [ v1alpha1 ]
        operations: [ CREATE,UPDATE ]
        resources: [ rules ]
        scope: Namespaced
  - name: validtating.{{.Values.name}}.configs.v1alpha1
    admissionReviewVersions: [ v1 ]
    sideEffects: None
    timeoutSeconds: 15
    failurePolicy: Fail
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{.Values.name}}-apisix-controller
        namespace: {{.Release.Namespace}}
        path: /validating/apisix.apache.org/configs/v1alpha1
        port: 65443
    objectSelector:
      matchLabels:
        apisix.apache.org/controller-by: {{.Values.name}}
    rules:
      - apiGroups: [ apisix.apache.org ]
        apiVersions: [ v1alpha1 ]
        operations: [ UPDATE ,DELETE ]
        resources: [ configs ]
        scope: Cluster