#Apisix controller name#
name: default
#---------------------------------

#Apisix controller http listen port
httpPort: 9080
#---------------------------------

#Apisix controller https listen port
httpsPort: 9443
#---------------------------------

#Apisix controller tcp listen ports
tcpPorts:
  - port: 8888
#    tls: true
#  - port: 8888
#    tls: true
#  - port: 8889
#    hostPort: 9973
#    tls: false
#---------------------------------

#How Apisix controller expose
# enum [ LoadBalancer | HostPort | HostNetwork ]
exposeMode: HostPort
#---------------------------------

#Apisix controller worker process
workerProcesses: 1
#---------------------------------

replicas: 1

#Apisix controller resources
resources:
  requests:
    cpu: "1000m"
  #    memory: "1000M"
  limits:
    cpu: "1000m"
#    memory: "1000M"
#---------------------------------

#nodeMatchExpressions:
#  - key: kubernetes.io/hostname
#    operator: In
#    values:
#      - node8.67
image: placehodler