name: default
httpPort: 9080  #Apisix controller http listen port
httpsPort: 9443 #Apisix controller https listen port
exposeMode: HostPort # enum [ LoadBalancer | HostPort | HostNetwork ]
workerProcesses: 1
replicas: 1
resources:
  requests:
    cpu: "1000m"
  limits:
    cpu: "1000m"
image:
# nodeMatchExpressions:
#   - key: kubernetes.io/hostname
#     operator: In
#     values:
#       - node-172.16.0.238   